feat(nameservice): implemented nameservice-crypto, nameservice-transactions and nameservice-api
protokol/nameservice pull request #4
Opened 2021-03-01 14:44 UTC by KovacZan

## Summary

Implemented nameservice.
It adds a name to wallet that sends the transaction, which can be then used for api searching.

I have implemented the following packages:
- nameservice-crypto
- nameservice-transactions
- nameservice-api

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

2021-03-02 13:58 UTC, kristjank commented
👏

2021-03-03 13:32 UTC, amacar requested changes

2021-03-03 13:32 UTC, amacar commented on packages/nameservice-crypto/src/enums.ts
> +const namesericeStaticFee: any = defaults.nameserviceStaticFee.toString();
typo, change to `nameserviceStaticFee` also change type to string

2021-03-03 13:32 UTC, amacar commented on packages/nameservice-crypto/package.json
> +        "@protokol/utils": "^1.0.0-beta.37",
Use latest version (.38).

2021-03-03 13:32 UTC, amacar commented on packages/nameservice-api/src/resources/nameservice.ts
> +        return {
do we need all this data in the nameservice response?

2021-03-04 12:31 UTC, amacar approved these changes

2021-03-04 12:33 UTC, merged